config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:create, :update, :edit, :destroy]
  get 'comments/:id/edit' => "comments#edit"
  # コメント編集ページ
  post 'comments/:id/destroy' => 'comments#destroy'
  
  resources :users
  get '/login' => 'users#login_form'
  # ユーザーのログイン
  post '/login' => 'users#login'
  # ログイン情報を受け取る
  post '/logout' => 'users#logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'posts/index' => 'posts#index'
  # 投稿一覧ページ
  get 'posts/new' => 'posts#new'
  # 新規投稿ページ
  post 'posts/create' => 'posts#create'
  # 投稿内容を受け取る
  get 'posts/:id' => 'posts#show'
  # 投稿詳細ページ
  get 'posts/:id/edit' => 'posts#edit'
  # 投稿編集ページ
  post 'posts/:id/update' => 'posts#update'
  # 編集後の投稿内容を受け取る
  post 'posts/:id/destroy' => 'posts#destroy'
  # 投稿内容の削除
  get '/' => 'home#top'
  # トップページ
  get '/about' => 'home#about'
  # サービス紹介ページ
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # validates :content, {presence: true, length:{maximum: 140}}
  belongs_to :user
  belongs_to :post, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, {presence: true, length:{maximum: 140}}
  validates :user_id, {presence: true}
  has_many :comments
  
  def user
    return User.find_by(id: self.user_id)
    # インスタンスメソッドを定義することで投稿に紐づいているuser情報が表示される
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, {presence: true}
  validates :email, {presence: true, uniqueness: true}
  validates :password, {presence: true}
  
  # validates :introduce, {presence: true, length:{maximum: 255}}
  # validates :product, {presence: true, length:{maximum: 50}}
  # validates :game_mode, {presence: true, length:{maximum: 50}}
  has_many :comments
  
  def posts
    return Post.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  # 「before_action :メソッド」でアクションの処理を共通化することができる
  add_flash_types :success, :danger
  # フラッシュメッセージ
  def set_current_user
    # ログインしているユーザー
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def authenticate_user
    # アクセス制限のメソッド
    if @current_user == nil
      flash[:danger] = "ログインしてください"
      redirect_to("/login")
    end
  end
  
  def forbit_login_user
    # ログインユーザーがアクセスできない
    if @current_user
      flash[:success] = "ログイン済みです"
      redirect_to("/posts/index")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = @current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_to("/posts/index")

    else
      flash[:danger] = "コメントできませんでした"
      render("/posts/show")
      # コメント入力viewに戻る
    end
  
  
  def edit
    @comment = Comment.find_by(id: params[:id])
  end
  
  def update
    @comment = Comment.find_by(id: params[:id])
    @comment.content = params[:content]
    if @comment.save
      flash[:success] = "編集に成功しました"
      redirect_to("/posts/index")
    else
      flash[:danger] = "編集に失敗しました"
      render("/commets/edit")
    end
  end
    
    def destroy
      @comment = Comment.find_by(id: params[:id])
      @comment.destroy
      redirect_to("/posts/index")
    end
  end
  
  
  
  
  
  
  
  
  
  
  
  private
  
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :forbit_login_user, {only: [:top]}
  
  def top
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def show
    @post = Post.find_by(id: params[:id])
    @user = @post.user
    # ユーザー情報をuserテーブルから取得しshow.html.erb内で表示する
    @comments = @post.comments
    @comment = @post.comments.build
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(
    content: params[:content],
    user_id: @current_user.id
    # 新規投稿をログインユーザーに紐付け
    )
    if @post.save
      flash[:success]="投稿に成功しました"
      redirect_to("/posts/index")
    else
      render("/posts/new")
    end
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
        flash[:success]="編集に成功しました"
        # 変数flash
      redirect_to("/posts/index")
    else
      render("/posts/edit")
    #   renderメソッドをつけることで直前の投稿を表示できる
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to("/posts/index")
  end
  
  def ensure_correct_user
    # 正しいユーザーか確かめる
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:danger] = "あなたに権限はありません"
      redirect_to("/posts/index")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  # onlyをつけることで指定したアクションでのみメソッドを使うことができる
  before_action :forbit_login_user, {only: [:new, :create, :login, :login_form]}
  
  before_action :ensure_correct_user, {only: [:edit, :update]}

  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      image_name: "default_user.jpg"
      )
    if @user.save
      session[:user_id] = @user.id
      flash[:success]="ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render("/users/new")
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.introduce = params[:introduce]
    @user.product = params[:product]
    @user.game_mode = params[:game_mode]
    # if params[:image]
    #   @user.image_name = "#{@user.id}.jpg"
    #   image = params[:image]
    #   File.binwrite("public/user_images/#{@user.image_name}", image&.read)
    # end
    
    if @user.save
      flash[:success]="更新が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render("/users/edit")
    end
  end
  
  def login_form
  end
  
  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      # 変数session→ログイン後ページが変わってもログイン状態を維持
      flash[:success] = "ログインに成功しました"
      redirect_to("/posts/index")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
      # 文字を維持したまま返す
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to("/login")
  end
  
  def ensure_correct_user
    # 正しいユーザーか確かめるメソッド
    if @current_user.id != params[:id].to_i
      # paramsは文字列として持ってくるのでidを数列にするためには「.to_i」をつける
      # 「!=」は"等しくないという"意味
      flash[:danger] = "あなたに権限はありません"
      redirect_to("/posts/index")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
コメント編集ページ

app/views/home/about.html.erb
<!--<!doctype html>-->
<!--<html lang="ja">-->
<!--  <head>-->
    <!-- Required meta tags -->
<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->

    <!-- Bootstrap CSS -->
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">-->

<!--    <title>Hello, world!</title>-->
<!--  </head>-->
<!--  <body>-->
<!--    <h1>Hello, world!</h1>-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!--    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>-->
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>-->
<!--  </body>-->
<!--</html>-->

app/views/home/top.html.erb
<!--<head>-->
<!--  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">-->
<!--  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />-->
<!--</head>-->


<div class="jumbotron jumbotron-fullheight jumbo-vertical-center text-light text-center bg-dark mb-0 radius-0 ht-tm-jumbotron">
  <div class="container">
    <div class="ht-tm-header">
      <h1 class="display-2 text-light text-uppercase">Let's play COD</h1>
      <span class="lead lead-lg">Find your friends and play with them</span>
      <div class="mt-4">
        <a href="#" class="btn btn-danger btn-lg m-2 btn-wide js-ht-download-link" data-type="theme" data-id="94">Sign Up</a>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="example col-md-10 ml-auto mr-auto">
    <div class="row">
     <div class="col-md-4 mt-4">
       <div class="h-caption">
         <h4><i class=" fas fa-shield-alt fa-3x fa-flip-horizontal faa-pulse animated "></i><br>Reliability</h4>
       </div>
     </div>
     <div class="col-md-4 mt-4">
       <div class="h-caption">
         <h4><i class=" fas fa-street-view fa-3x fa-flip-horizontal faa-pulse animated "></i><br>Found</h4>
       </div>
     </div>
     <div class="col-md-4 mt-4">
       <div class="h-caption">
         <h4><i class=" fas fa-gamepad fa-3x fa-flip-horizontal faa-pulse animated "></i><br>Enjoy</h4>
       </div>
     </div>
    </div>
  </div>
</div>


<footer>
	<div class="container">
		<div class="row">
  		<div class="col-md-6 mt-5 offset-md-2">
  			<p>Copyright © 2020, Call of Duty. Design:</p>
  		</div>
		</div>
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="https://231cffa1e9ae4866b94635b52532f22d.vfs.cloud9.ap-northeast-1.amazonaws.com/">Want to play COD</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!--Navbar-->

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <% if @current_user %>
      <!--<li class="nav-item active">-->
      <!--  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      <!--</li>-->
        <li class="nav-item">
          <%= link_to "Post New", posts_new_path, class: 'nav-link disabled' %>
        </li>      
        <li class="nav-item">
          <%= link_to @current_user.name, ("/users/#{@current_user.id}"), class: 'nav-link disabled' %>
          <!--変数は""で囲むと文字列として認識されるからつけない-->
        </li>
        <li class="nav-item">
          <%= link_to "ALl Posts", posts_index_path, class: 'nav-link disabled' %>
        </li>  
        <li class="nav-item">
          <%= link_to "All User", users_path, class: 'nav-link disabled' %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, method: :post, class: 'nav-link disabled' %>
        </li>
          <% else %>
        <li class="nav-item">
          <%= link_to "Call of Duty", about_path, class: 'nav-link disabled' %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: 'nav-link disabled' %>
        </li>
        <li class="nav-item">
          <%= link_to "Signup", new_user_path, class: 'nav-link disabled' %>
        </li>
        <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <!--ナビゲーションバー-->
    
    
    <% if flash[:success] %>
      <div class="alert alert-success">
        <%= flash[:success] %>
      </div>
    <% elsif flash[:danger] %> 
      <div class="alert alert-danger">

        <%= flash[:danger] %>
      </div>
    <% end %>
    <!--フラッシュメッセージ-->    
    
      
    

      <%= yield %>
      
  </body>
</html>

app/views/posts/edit.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="errors-text">
        <% @post.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
        </div>
      </div>
      <div class="col-md-6 offset-md-3">
        <%= form_tag("/posts/#{@post.id}/update") do %>
          <textarea class="textlines" name="content"><%= @post.content %></textarea>
          <input class ="new-submit" type="submit" value="Post">
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mt-5 offset-md-3">
        <% @posts.each do |post| %>
          <div class="posts-index-item">
            <div class="post-left">
              <img src="<%= "/user_images/#{post.user.image_name}" %>">
            </div>
            <div class="post-right">
              <div class="post-user-name">
                <%= link_to(post.user.name, "/users/#{post.user.id}") %>
              </div>
            <%= link_to(post.content, "/posts/#{post.id}") %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<!--<% @post.errors.full_messages.each do |message| %>-->
<!--<%= message %>-->
<!--<% end %>-->


<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 mt-5 offset-md-3">
        <div class="errors-text">
          
        <% @post.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
        </div>
      </div>

    <div class="col-md-6 offset-md-3">
      <%= form_tag("/posts/create") do %>
        <textarea class="textlines" name="content"></textarea>

          <input class ="new-submit" type="submit" value="Post">
      <% end %>
    </div>
    </div>
  </div>
</body>

app/views/users/edit.html.erb
<% @user.errors.full_messages.each do |message| %>
  <%= message %>
<% end %>



    		

	      <%= form_tag(user_path(@user.id), method: :patch) do %>
	        <p>ユーザー名</p>
	        <input name="name" value="<%= @user.name %>">
	        <p>メールアドレス</p>
	        <input name="email" value="<%= @user.email %>">
	        <p>ゲームタイトル</p>
	        <input name="product" value="<%= @user.product %>">
	        <p>ゲームモード</p>
	        <input name="game_mode" value="<%= @user.game_mode %>">
	        <p>自己紹介</p>
	        <input name="introduce" value="<%= @user.introduce %>">
	        <p>プロフィール画像</p>
	        <input name="image" type="file"><br>
	        <input type="submit" value="保存">
			<% end %>


<body class="bg-light">

    <div class="container">

      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
 

              <div class="input-group-append">
              </div>
            </div>

        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Profile edit</h4>
          <form class="needs-validation" novalidate="">
            <div class="row">
              <div class="col-md-6 mb-3">
                <div class="invalid-feedback">
                </div>
              </div>
              
              <div class="col-md-6 mb-3">
                <div class="invalid-feedback">
                </div>
              </div>
            </div>

<!--ユーザーネーム-->
            <div class="mb-3">
              <label for="username">Username</label>
              <div class="input-group">
                <input type="text" class="form-control" id="username" placeholder="username" value="<%= @user.name %>">
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
              </div>
            </div>
						
<!--メールアドレス-->
            <div class="mb-3">
              <label for="email">Email</label>
              <input type="text" class="form-control" id="email" placeholder="you@example.com" value="<%= @user.email %>">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

<!--好きなゲームタイトル-->
            <div class="mb-3">
              <label for="product">Like Game Title</label>
              <input type="text" class="form-control" id="product" placeholder="MW,BO4 etc.." value="<%= @user.product %>">
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

<!--好きなゲームモード-->
            <div class="mb-3">
              <label for="game_mode">Like Game Mode</label>
              <input type="text" class="form-control" id="game_mode" placeholder="TDM,S&D etc..." value="<%= @user.game_mode %>">
            </div>

            <div class="row">
              <div class="col-md-3 mb-3">
                <label for="game_title">Like Game Title</label>
                <select class="custom-select d-block w-100" id="game_title" required="">
                  <option value="">
                  <option>MW</option>
                  <option>BO4</option>
                  <option>WWII</option>
                  <option>MWR</option>
                  <option>IW</option>
                  <option>BO3</option>
                  <option>AW</option>
                  <option>Ghost</option>
                  <option>BO2</option>
                  <option>MW3</option>
                  <option>BO</option>
                  <option>MW2</option>
                  <option>WAW</option>
                  <option>COD4</option>
                </select>
              </div>
              
              <div class="col-md-3 mb-3">
                <label for="game_mode">Like Game Mode</label>
                <select class="custom-select d-block w-100" id="game_mode" required="">
                  <option value="">
                  <option>TEAM DEATH MATCH</option>
                  <option>DOMINATION</option>
                  <option>SEATH & DESTROY</option>
                  <option>KILL CONFIRMED</option>
                  <option>HARDPOINT</option>
                  <option>SR 2on2</option>
                  <option>混合</option>
                  <option>その他</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
              
              <div class="col-md-3 mb-3">
                <label for="weapon">Like Weapon</label>
                <select class="custom-select d-block w-100" id="weapon" required="">
                  <option value="">
                 	<option>SMG</option>
                 	<option>AR</option>
                 	<option>LMG</option>
                 	<option>SR</option>
                 	<option>SG</option>
                 	<option>Knife</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
              <div class="col-md-3 mb-3">
								<label for="user_icon">User Icon</label>
								<input name="image" type="file">
              </div>

              <label for="username">Introduce</label>
              <textarea class="form-control" rows="3" placeholder="Hello World!" value="<%= @user.introduce %>"></textarea>
    
              
              <div class="col-md-3 mb-3">
              </div>
            </div>
            
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Save</button>
          </form>
        </div>
      </div>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
    
  

</body>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mt-5 offset-md-3">
      <% @users.each do |user| %>
        <div class="posts-index-item">
          <div class="post-left">
            <img src="<%= "/user_images/#{user.image_name}" %>">
          </div>
          <div class="post-right">
            <%= link_to(user.name, "/users/#{user.id}") %>
            <p>ここに自己紹介の一部を掲載</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/login_form.html.erb
<body class="body-container">
  <% if @error_message %>
    <%= @error_message %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <h1 class="text-center">LOGIN</h1>
        <%= form_tag("/login") do %>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></span>
          <input type="text" class="form-control" name="email" placeholder="username" value="<%= @email %>">
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
          <input type="password" class="form-control" name="password" placeholder="password" value="<%= @password %>">
        </div>
        
        <!--make a row-->
        <div class="row">
          <div class="col-md-6">
            <input type="checkbox"> <small>Remember me</small>
          </div>
          <div class="col-md-6">
            <a href="https://231cffa1e9ae4866b94635b52532f22d.vfs.cloud9.ap-northeast-1.amazonaws.com/users/new">
              <p class="text-right">Create an account</p></a>
          </div>
        </div>

        <input type="submit" class="btn btn-danger btn-lg btn-block mt-3" value="Login" >
        <% end %>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</body>


<!--<% if @error_message %>-->
<!-- <%= @error_message %>-->
<!--<% end %>-->

app/views/users/new.html.erb
<!--<body class="body-container">-->
<!--  <div class="container">-->
<!--    <div class="row">-->
<!--      <div class="col-md-3"></div>-->
<!--      <div class="col-md-6">-->
<!--        <h1 class="text-center">SIGN UP</h1>-->
<!--        <div class="input-group">-->
<!--          <span class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>-->
<!--          <input type="text" class="form-control" name="username" placeholder="username" value="<%= @username %>">-->
<!--        </div>-->
<!--        <div class="input-group">-->
<!--          <span class="input-group-addon"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></span>-->
<!--          <input type="text" class="form-control" name="email" placeholder="email" value="<%= @email %>">-->
<!--        </div>-->
<!--        <div class="input-group">-->
<!--          <span class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>-->
<!--          <input type="password" class="form-control" name="email" placeholder="password" value="<%= @password %>">-->
<!--        </div>-->
<!--        <div class="row">-->
<!--          <div class="col-md-6">-->
<!--            <input type="checkbox"> <small>Remember me</small>-->
<!--          </div>-->
<!--          <div class="col-md-6">-->
<!--            <a href="https://231cffa1e9ae4866b94635b52532f22d.vfs.cloud9.ap-northeast-1.amazonaws.com/login">-->
<!--              <p class="text-right">have an account</p></a>-->
<!--          </div>-->
<!--        </div>-->
<!--          <a href="#"><div class="btn btn-danger">Signup</div></a>-->
          
<!--        </div>-->
<!--      </div>-->
<!--      <div class="col-md-3"></div>-->
<!--    </div>-->
<!--  </div>-->
<!--</body>-->








<h1>新規ユーザー登録ページ</h1>

<% @user.errors.full_messages.each do |message| %>
  <%= message %>
<% end %>

<%= form_with url: users_path, method: :post, local: true do |form| %>

  <p>ユーザー名</p>
  <input name="name" value="<%= @user.name %>">
  <p>メールアドレス</p>
  <input name="email" value="<%= @user.email %>">
  <p>パスワード</p>
  <input name="password" type="password" value="<%= @user.password %>"><br>

  <input type="submit" value="新規登録">
<% end %>